#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from settings.ui on Wed May  6 23:27:06 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_gcal_settings(object):
    def setupUi(self, gcal_settings):
        gcal_settings.setObjectName("gcal_settings")
        gcal_settings.resize(380, 280)
        self.verticalLayout_3 = QtGui.QVBoxLayout(gcal_settings)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(108, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lbl_icon = QtGui.QLabel(gcal_settings)
        self.lbl_icon.setPixmap(QtGui.QPixmap(":/icons/preferences-contact-list.png"))
        self.lbl_icon.setObjectName("lbl_icon")
        self.horizontalLayout.addWidget(self.lbl_icon)
        spacerItem1 = QtGui.QSpacerItem(98, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.lbl_explanation = QtGui.QLabel(gcal_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_explanation.sizePolicy().hasHeightForWidth())
        self.lbl_explanation.setSizePolicy(sizePolicy)
        self.lbl_explanation.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lbl_explanation.setWordWrap(True)
        self.lbl_explanation.setObjectName("lbl_explanation")
        self.verticalLayout_3.addWidget(self.lbl_explanation)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_email = QtGui.QLabel(gcal_settings)
        self.lbl_email.setObjectName("lbl_email")
        self.verticalLayout_2.addWidget(self.lbl_email)
        self.lbl_password = QtGui.QLabel(gcal_settings)
        self.lbl_password.setObjectName("lbl_password")
        self.verticalLayout_2.addWidget(self.lbl_password)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.le_email = QtGui.QLineEdit(gcal_settings)
        self.le_email.setObjectName("le_email")
        self.verticalLayout.addWidget(self.le_email)
        self.le_password = QtGui.QLineEdit(gcal_settings)
        self.le_password.setEchoMode(QtGui.QLineEdit.Password)
        self.le_password.setObjectName("le_password")
        self.verticalLayout.addWidget(self.le_password)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.lbl_email.setBuddy(self.le_email)
        self.lbl_password.setBuddy(self.le_password)

        self.retranslateUi(gcal_settings)
        QtCore.QMetaObject.connectSlotsByName(gcal_settings)

    def retranslateUi(self, gcal_settings):
        gcal_settings.setWindowTitle(kdecore.i18n("Google Calendar Settings"))
        self.lbl_explanation.setText(kdecore.i18n("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter your Google username. If you have a GMail account, <span style=\" font-style:italic;\">@gmail.com</span> is optional. If you have Google Apps hosted on your own domain, simply enter your email address for that domain.</p></body></html>"))
        self.lbl_email.setText(kdecore.i18n("&Email:"))
        self.lbl_password.setText(kdecore.i18n("&Password:"))

import settings_rc
