#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from settings.ui on Wed May  6 20:39:17 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_gcal_settings(object):
    def setupUi(self, gcal_settings):
        gcal_settings.setObjectName("gcal_settings")
        gcal_settings.resize(360, 240)
        self.widget = QtGui.QWidget(gcal_settings)
        self.widget.setGeometry(QtCore.QRect(4, 0, 351, 238))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(self.widget)
        self.label.setPixmap(QtGui.QPixmap(":/preferences-contact-list.png"))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_email = QtGui.QLabel(self.widget)
        self.lbl_email.setObjectName("lbl_email")
        self.verticalLayout_2.addWidget(self.lbl_email)
        self.lbl_password = QtGui.QLabel(self.widget)
        self.lbl_password.setObjectName("lbl_password")
        self.verticalLayout_2.addWidget(self.lbl_password)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.le_email = QtGui.QLineEdit(self.widget)
        self.le_email.setObjectName("le_email")
        self.verticalLayout.addWidget(self.le_email)
        self.le_password = QtGui.QLineEdit(self.widget)
        self.le_password.setEchoMode(QtGui.QLineEdit.Password)
        self.le_password.setObjectName("le_password")
        self.verticalLayout.addWidget(self.le_password)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.lbl_email.setBuddy(self.le_email)
        self.lbl_password.setBuddy(self.le_password)

        self.retranslateUi(gcal_settings)
        QtCore.QMetaObject.connectSlotsByName(gcal_settings)

    def retranslateUi(self, gcal_settings):
        gcal_settings.setWindowTitle(kdecore.i18n("Google Calendar Settings"))
        self.lbl_email.setText(kdecore.i18n("&Email:"))
        self.lbl_password.setText(kdecore.i18n("&Password:"))

import settings_rc
